Add a tip explaining HTTP Only cookies issue
Watching the Discord, I see this issue coming up fairly frequently, when someone is developing a front end app locally, and their app suddenly stops working with the message

> Error: "refresh_token" is required in either the JSON payload or Cookie

This tip explains the cause of the issue, and two different workarounds.