Add mysqli to requirements
Add `mysqli` to requirements

"ruckusing-migrations" requires mysqli or fails with
```
Fatal error: Class 'mysqli' not found in
vendor/directus/migrations/lib/Ruckusing/Adapter/MySQL/MySQLBase.php
on line 1294
```